### ISSUE TITLE
More helpful Views exceptions when inputs are invalid

### ISSUE THREAD

**Issue by etarena** [imglib/imglib2#141]
We invoking Views methods it would be nice to have more input validation upfront to avoid exceptions like the following:
```
java.lang.ArrayIndexOutOfBoundsException: 2
	at net.imglib2.AbstractInterval.min(AbstractInterval.java:182)
	at net.imglib2.util.Intervals.contains(Intervals.java:374)
	at net.imglib2.img.array.ArrayImg.fastCursorAvailable(ArrayImg.java:188)
	at net.imglib2.img.array.ArrayImg.supportsOptimizedCursor(ArrayImg.java:230)
	at net.imglib2.view.iteration.IterableTransformBuilder.buildIterableInterval(IterableTransformBuilder.java:237)
	at net.imglib2.view.iteration.IterableTransformBuilder.getEfficientIterableInterval(IterableTransformBuilder.java:77)
	at net.imglib2.view.IntervalView.getFullViewIterableInterval(IntervalView.java:137)
	at net.imglib2.view.IntervalView.iterationOrder(IntervalView.java:156)
	at net.imglib2.view.Views.flatIterable(Views.java:765)
	at net.imglib2.img.ImgView.<init>(ImgView.java:81)
```
This exception results from an attempt to call `Views.interval(img, min, max)` where `img.numDimensions() == 3` and `min.length == max.length == 2`.

**Comment by axtimwalde** [comment]
Please test these conditions outside of the Views framework where necessary.  We do not want to perform runtime tests where inputs can be guaranteed to be correct.
