### ISSUE TITLE
LanczosInterpolator crashes

### ISSUE THREAD

**Issue by tpietzsch** [imglib/imglib2#212]
It seems that `LanczosInterpolator` is broken. The following simple example crashes:
```java
import net.imglib2.RealRandomAccess;
import net.imglib2.img.Img;
import net.imglib2.img.array.ArrayImgs;
import net.imglib2.interpolation.randomaccess.LanczosInterpolatorFactory;
import net.imglib2.type.numeric.real.FloatType;
import net.imglib2.view.Views;

public class FAILS
{
	public static void main( final String[] args )
	{
		final Img< FloatType > img = ArrayImgs.floats( 10 );
		final RealRandomAccess< FloatType > a = Views.interpolate( Views.extendBorder( img ), new LanczosInterpolatorFactory<>() ).realRandomAccess();
		a.setPosition( new int[] { 5 } );
		a.get();
	}
}
```
It throws
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 41
	at net.imglib2.interpolation.randomaccess.LanczosInterpolator.lookUpLanczos(LanczosInterpolator.java:224)
	at net.imglib2.interpolation.randomaccess.LanczosInterpolator.get(LanczosInterpolator.java:188)
	at net.imglib2.interpolation.randomaccess.LanczosInterpolator.get(LanczosInterpolator.java:50)
	at t4realviews.FAIL.main(FAIL.java:31)
```
Apparently this hasn't anything todo with size or dimensionality of the image.

@StephanPreibisch Do you want to fix it? Or should we just remove it. (Apparently nobody is using it or they would have discovered this problem...)

**Comment by StephanPreibisch** [comment]
Hi, I’ll try to have a look at it, sometimes it is useful to try if it is an interpolation artifact ....

**Comment by axtimwalde** [comment]
I guess this is my fault.  Table not long enough?

**Comment by axtimwalde** [comment]
However, I am wondering why it broke just now---used to work in all sorts of contexts?

**Comment by tpietzsch** [comment]
> I guess this is my fault. Table not long enough?

@axtimwalde Can you explain? Why is it your fault?
I tried to look at the history of LanczosInterpolator and it has not changed for years, apparently.

**Comment by ctrueden** [comment]
I was also confused, because we use the `LanczosInterpolatorFactory` in the Ops notebooks, and it has always worked great. I posted some working code in the PR #213.

**Comment by axtimwalde** [comment]
@tpietzsch because I wrote the lookup stuff to make it faster.  It's very possible that I did not consider specific edge cases.
