### ISSUE TITLE
Bug in Views.flatIterable()

### ISSUE THREAD

**Issue by StephanPreibisch** [imglib/imglib2#257]
Just found out that this causes an Exception ... I'll look into it as well, just wanted to share it also:

		// ARRAY img
		final Img< FloatType > array = new ArrayImgFactory< FloatType >( new FloatType() ).create( new long[] { 100, 10 } );

		// works
		final Cursor< FloatType > cursor1a = array.cursor();
		cursor1a.copyCursor();

		// works
		final Cursor< FloatType > cursor2a = Views.flatIterable( array ).cursor();
		cursor2a.copyCursor();

		// CELL img
		final Img< FloatType > cell = new CellImgFactory< FloatType >( new FloatType(), 8, 8 ).create( new long[] { 100, 10 } );

		// works
		final Cursor< FloatType > cursor1b = cell.cursor();
		cursor1b.copyCursor();

		// works
		final Cursor< FloatType > cursor2b = Views.flatIterable( cell ).cursor();
		cursor2b.fwd();
		cursor2b.copyCursor();

		// FAILS when copying Cursor
		final Cursor< FloatType > cursor3b = Views.flatIterable( cell ).cursor();
		cursor3b.copyCursor();

		// also FAILS when copying Cursor
		final Cursor< FloatType > cursor4b = Views.flatIterable( Views.interval( Views.extendZero( cell ), cell ) ).cursor();
		cursor4b.copyCursor();

The exception is:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at net.imglib2.img.list.ListImg.get(ListImg.java:99)
	at net.imglib2.img.list.ListRandomAccess.get(ListRandomAccess.java:81)
	at net.imglib2.img.cell.CellRandomAccess.getCell(CellRandomAccess.java:136)
	at net.imglib2.img.cell.CellRandomAccess.getCell(CellRandomAccess.java:50)
	at net.imglib2.img.cell.AbstractCellImg.update(AbstractCellImg.java:86)
	at net.imglib2.type.numeric.real.FloatType.updateContainer(FloatType.java:90)
	at net.imglib2.img.cell.CellRandomAccess.<init>(CellRandomAccess.java:103)
	at net.imglib2.img.cell.CellRandomAccess.copy(CellRandomAccess.java:148)
	at net.imglib2.img.cell.CellRandomAccess.copyRandomAccess(CellRandomAccess.java:154)
	at net.imglib2.img.cell.CellRandomAccess.copyRandomAccess(CellRandomAccess.java:50)
	at net.imglib2.view.RandomAccessibleIntervalCursor.<init>(RandomAccessibleIntervalCursor.java:85)
	at net.imglib2.view.RandomAccessibleIntervalCursor.copy(RandomAccessibleIntervalCursor.java:161)
	at net.imglib2.view.RandomAccessibleIntervalCursor.copyCursor(RandomAccessibleIntervalCursor.java:167)
	at net.imglib2.view.RandomAccessibleIntervalCursor.copyCursor(RandomAccessibleIntervalCursor.java:54)

**Comment by StephanPreibisch** [comment]
It is caused because CellRandomAccess.copyRandomAccess() fails when it is outside of the Interval, which it is here because the Cursor of Views.flatIterable() is set to be at -1 in dim=0.

**Comment by StephanPreibisch** [comment]
Here is a way to fix it by fixing the RandomAccessibleIntervalCursor, which now checks that it is inside its own interval before calling the copyRandomAccess() method ... the question is, should we fix the CellRandomAccess instead? @tpietzsch @axtimwalde 

https://github.com/imglib/imglib2/commit/6d943faece58b36414df52795cb152c5b2cd4a77

**Comment by StephanPreibisch** [comment]
after talking to @tpietzsch, maybe this will fix itself with the new iteration of the CellImg Random-access & cursor that do not immediately grab the cell, but only when actually calling get(). For now, I can continue with that branch ...

**Comment by tpietzsch** [comment]
I fixed it in the `CellRandomAccess`.

**Comment by tpietzsch** [comment]
@StephanPreibisch Please delete your branch when you don't need it anymore
