### ISSUE TITLE
ArrayImg with negative dimensions is possible

### ISSUE THREAD

**Issue by ctrueden** [imglib/imglib2#276]
```java
Img<UnsignedByteType> img = ArrayImgs.unsignedBytes(-3, -2);
for (UnsignedByteType t : img)
	System.out.println(t);
```
prints:
```
0
0
0
0
0
0
```

But:
```java
Img<UnsignedByteType> img = ArrayImgs.unsignedBytes(-3, 2);
for (UnsignedByteType t : img)
	System.out.println(t);
```
prints:
```
Exception in thread "main" java.lang.NegativeArraySizeException
	at net.imglib2.img.basictypeaccess.array.AbstractByteArray.<init>(AbstractByteArray.java:50)
	at net.imglib2.img.basictypeaccess.array.ByteArray.<init>(ByteArray.java:46)
	at net.imglib2.img.basictypeaccess.array.ByteArray.createArray(ByteArray.java:57)
	at net.imglib2.img.basictypeaccess.array.ByteArray.createArray(ByteArray.java:42)
	at net.imglib2.img.array.ArrayImgFactory.create(ArrayImgFactory.java:91)
	at net.imglib2.img.array.ArrayImgFactory.create(ArrayImgFactory.java:68)
	at net.imglib2.img.array.ArrayImgs.unsignedBytes(ArrayImgs.java:107)
	at net.restlesscoder.sandbox.Sandbox.main(Sandbox.java:11)
```

Probably we should assert all lengths > 0 when creating new images.

**Comment by hanslovsky** [comment]
I am working on a PR, we can discuss the details once I open the PR.
